sonar.projectKey=gicamm_homeassistant-comelit
sonar.projectName=HomeAssistant Comelit
sonar.sources=.
sonar.exclusions=**/venv/**,**/__pycache__/**,**/*.pyc,**/.pytest_cache/**,**/.tox/**,**/.eggs/**,**/.mypy_cache/**,**/.coverage,**/build/**,**/dist/**,.git,.github,**/venv/**,**/test/**,**/coverage.xml
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3
sonar.projectVersion=master
