name: Validate with HACS

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS Action
        uses: hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa  # main
        with:
          category: "integration"
